spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: olfd
    password: olfd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

application:
  available-roles:
    - "ROLE_ADMIN"
    - "ROLE_CLIENT"
    - "ROLE_CARRIER"
    - "ROLE_PRODUCER"