server:
  port: 8999
spring:
  application:
    name: carriage-service
  data:
    mongodb:
        database: "admin"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/