server:
  port: 8999
spring:
  application:
    name: carriage-service
  data:
    mongodb:
      database: "admin"
      username: "olfd"
      password: "olfd"
      host: "localhost"
      port: 27017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/